enum_discrim_align_threshold = 20
format_code_in_doc_comments  = true
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
imports_layout               = "Vertical"
match_block_trailing_comma   = true
overflow_delimited_expr      = true
reorder_impl_items           = true
struct_field_align_threshold = 20
struct_lit_single_line       = false
struct_lit_width             = 0
struct_variant_width         = 0
unstable_features            = true
use_field_init_shorthand     = true
wrap_comments                = true
